#!/usr/bin/env bash
#
# One-time server bootstrap for Money Tracker on a fresh Amazon Linux 2023
# EC2 instance (t3.micro, Free Tier). Run it ONCE, right after you SSH in:
#
#   curl -fsSL <raw-url>/setup-server.sh -o setup-server.sh   # or scp it up
#   chmod +x setup-server.sh
#   sudo ./setup-server.sh
#
# It installs Java 21 + PostgreSQL, adds swap (1 GB RAM is too tight without
# it), creates the database, and lays down the systemd service. It does NOT
# start the app yet — you upload the jar and set secrets afterwards (see README).
#
# Safe to re-run: every step checks before acting.
set -euo pipefail

APP_USER="moneytracker"
APP_DIR="/opt/money-tracker"
DB_NAME="moneytracker"
DB_USER="moneytracker"

if [[ $EUID -ne 0 ]]; then
  echo "Please run with sudo: sudo ./setup-server.sh" >&2
  exit 1
fi

echo "==> [1/6] Creating 2 GB swap (prevents out-of-memory on a 1 GB instance)"
if [[ ! -f /swapfile ]]; then
  dd if=/dev/zero of=/swapfile bs=1M count=2048 status=progress
  chmod 600 /swapfile
  mkswap /swapfile
  swapon /swapfile
  grep -q '/swapfile' /etc/fstab || echo '/swapfile none swap sw 0 0' >> /etc/fstab
else
  echo "    swapfile already exists, skipping"
fi

echo "==> [2/6] Installing Amazon Corretto 21 (JDK) and PostgreSQL 15"
dnf install -y java-21-amazon-corretto-headless postgresql15 postgresql15-server

echo "==> [3/6] Initializing PostgreSQL (first run only)"
if [[ ! -f /var/lib/pgsql/data/PG_VERSION ]]; then
  postgresql-setup --initdb
fi
# The default pg_hba.conf uses 'ident' for TCP loopback, which rejects the
# app's JDBC password login. Switch loopback rules to scram-sha-256.
HBA=/var/lib/pgsql/data/pg_hba.conf
sed -i -E 's#^(host[[:space:]]+all[[:space:]]+all[[:space:]]+127\.0\.0\.1/32[[:space:]]+)ident#\1scram-sha-256#; s#^(host[[:space:]]+all[[:space:]]+all[[:space:]]+::1/128[[:space:]]+)ident#\1scram-sha-256#' "${HBA}"
systemctl enable --now postgresql

echo "==> [4/6] Creating database role + database (idempotent)"
# Password is read from $DB_PASSWORD if exported, otherwise we generate one and print it.
DB_PASSWORD="${DB_PASSWORD:-$(openssl rand -base64 18 | tr -d '/+=' | head -c 24)}"
sudo -u postgres psql -v ON_ERROR_STOP=1 <<SQL
DO \$\$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${DB_USER}') THEN
    CREATE ROLE ${DB_USER} LOGIN PASSWORD '${DB_PASSWORD}';
  END IF;
END \$\$;
SELECT 'CREATE DATABASE ${DB_NAME} OWNER ${DB_USER}'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${DB_NAME}')\gexec
SQL

echo "==> [5/6] Creating app user and ${APP_DIR}"
id -u "${APP_USER}" &>/dev/null || useradd --system --no-create-home --shell /usr/sbin/nologin "${APP_USER}"
mkdir -p "${APP_DIR}"
chown "${APP_USER}:${APP_USER}" "${APP_DIR}"

echo "==> [6/6] Writing systemd unit + environment template"
install -m 644 "$(dirname "$0")/money-tracker.service" /etc/systemd/system/money-tracker.service
if [[ ! -f "${APP_DIR}/money-tracker.env" ]]; then
  JWT_SECRET="$(openssl rand -base64 48 | tr -d '\n')"
  cat > "${APP_DIR}/money-tracker.env" <<ENV
# Generated by setup-server.sh. Edit APP_CORS_ORIGINS to your real frontend URL.
SPRING_PROFILES_ACTIVE=prod
SERVER_PORT=8080
DB_URL=jdbc:postgresql://localhost:5432/${DB_NAME}
DB_USERNAME=${DB_USER}
DB_PASSWORD=${DB_PASSWORD}
APP_JWT_SECRET=${JWT_SECRET}
APP_CORS_ORIGINS=*
# FIRST DEPLOY ONLY: uncomment to let Hibernate create the tables, then re-comment and restart.
# SPRING_JPA_HIBERNATE_DDL_AUTO=update
ENV
  chmod 600 "${APP_DIR}/money-tracker.env"
  chown "${APP_USER}:${APP_USER}" "${APP_DIR}/money-tracker.env"
fi
systemctl daemon-reload

echo
echo "============================================================"
echo " Server is ready. Database password (save it somewhere safe):"
echo "   ${DB_PASSWORD}"
echo
echo " Next: upload the jar to ${APP_DIR}/app.jar, then follow the"
echo " README from 'First deploy'. The env file (with a generated"
echo " JWT secret) is at ${APP_DIR}/money-tracker.env"
echo "============================================================"
